# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  release-on-stores:
    name: Release on stores
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: setup commit
        env:
          EVENT: ${{ toJson(github.event) }}
        run:
          echo "commit_message=\"Merge pull request \#1 from ISMA\"" >> $GITHUB_ENV
          
      - name: Dispatch event to release repo
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.REPOSITORY_DISPATCH }}
          script: |
            await github.rest.repos.createDispatchEvent({
              owner: 'Doozers',
              repo: 'mockRealease',
              event_type: 'Release on stores - Push on master',
              client_payload: {"commit_message":${{ env.commit_message }}},
            })
